### ISSUE TITLE
suggesting a fix in readme

### ISSUE THREAD

**Issue by timsu92** [ArchieMeng/waifu2x-ncnn-vulkan-python#4]
In class and `set_params` method, I think "noise" is better being changed to "denoise".
Although nihui uses this word too, the description corrects this.

**Comment by ArchieMeng** [comment]
Thanks for your suggestion. I didn't realize that it made confusion.
As it is a binding project, I will only change its related description and keep the variable name the same with waifu2x-ncnn-vulkan.
